client/urls.py
from django.contrib import admin
from django.urls import path
from client.apps import ClientConfig
from client.views import ClientListView, ClientCreateView, ClientUpdateView, \
    ClientDetailView, ClientDeleteView

app_name = ClientConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ClientListView.as_view(), name='list'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('view/<int:pk>/', ClientDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ClientUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='users')),
    path('client/', include('client.urls', namespace='client')),
    path('client_service/', include('client_service.urls', namespace='client_service')),
    path('materials/', include('materials.urls', namespace='materials')),
]
if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf.urls.static import static
from config import settings
from user.apps import UserConfig
from user.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, \
    UserConfirmEmailView, UserConfirmView, UserConfirmFailView, UserConfirmSentView, IndexView

app_name = UserConfig.name




urlpatterns = [

    path('', IndexView.as_view(), name='index_main'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),

    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmView.as_view(), name='email_confirmed'),
    path('email_info_failed/', UserConfirmFailView.as_view(), name='email_info_failed'),
    path('email_senting/', UserConfirmSentView.as_view(), name='email_senting'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models


from config import settings
NULLABLE = {'blank': True, 'null': True}

class Client(models.Model):
    """
    Клиент - получатель рассылки, которому будут отправляться рассылки
    """
    first_name = models.CharField(max_length=150, verbose_name='имя')
    last_name = models.CharField(max_length=150, verbose_name='фамилия')
    email = models.EmailField(verbose_name='почта', unique=True)
    message = models.TextField(max_length=700, verbose_name='комментарий')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.email})'


    class Meta:
        verbose_name = 'получатель'
        verbose_name_plural = 'получатели'
        ordering = ('last_name', 'first_name',)

client/forms.py
from django import forms
from .models import Client

class StyleFormMixin:
    """
    Миксин форма со стилем форм
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    """
    Форма для модели клиента
    """

    class Meta:
        model = Client
        exclude = ('owner',)

client/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from client.forms import ClientForm
from client.models import Client


class ClientListView(ListView):
    model = Client
    extra_context = {
        'title': 'Список клиентов'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter()
        return queryset

class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm

    extra_context = {
        'title': 'Add client'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('client:view', args=[self.object.pk])


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm

class ClientDetailView(DetailView):
    model = Client


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('client:list')

client/templates/client/client_confirm_delete.html
{% extends 'user/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Удалить клиента {{ object.last_name }}?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'client:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

client/templates/client/client_detail.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">

            <h5 class="card-title">email: {{ client.email }}</h5>
            <p class="card-text mb-3">Имя: {{ client.first_name|title }}</p>
            <p class="card-text mb-3">Фамилия: {{ client.last_name|title }}</p>
            <p class="card-text mb-3">Сообщение:
                {% if client.message %}
                {{ client.message }}
                {% else %}
                None
                {% endif %}</p>

        </div>
        <div class="card-footer">

            {% if request.user.is_staff %}
            <p class="card-text mb-3">owner: {{ client.owner }}</p>
            {% endif %}
            <a type="button" href="{% url 'client:list'%}"
               class="btn btn-lg btn-block btn-outline-primary">назад</a>

        </div>
    </div>
</div>

{% endblock %}

client/templates/client/client_form.html
{% extends 'user/base.html' %}

{% block content %}

<div class="text-center container">
    <form method="post" enctype="multipart/form-data">
        <div class="card col-8">
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if object %}
                        Изменить
                    {% else %}
                        Создать
                    {% endif %}
                </button>
                <a type="button" href="{% url 'client:list'%}"
                           class="btn btn-lg btn-block btn-outline-primary">Отмена</a>

            </div>
        </div>
    </form>
</div>

{% endblock %}

client/templates/client/client_list.html
{% extends 'user/base.html' %}
{% load my_tags %}
{% block content %}


<div class="text-center container">
    <a class="btn btn-primary mb-2" href="{% url 'client:create' %}" type="button" >Добавить клиента</a>
</div>


<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">Имя</th>
            <th scope="col">Фамилия</th>
            {% if request.user.is_staff %}
            <th scope="col">Owner</th>
            {% endif %}
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>

        {% for client in object_list %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ client.email }}</td>
            <td>{{ client.first_name|title }}</td>
            <td>{{ client.last_name|title }}</td>
            {% if request.user.is_staff %}
            <th>{{ client.owner }}</th>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'client:view' client.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Смотреть</a>
                    <a href="{% url 'client:edit' client.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Изменить</a>
                    <a href="{% url 'client:delete' client.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Удалить</a>

                </div>
            </td>
        </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}>