config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='users')),
    path('client/', include('client.urls', namespace='client')),
    path('client_service/', include('client_service.urls', namespace='client_service')),
    path('materials/', include('materials.urls', namespace='materials')),
]
if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path
from materials.apps import MaterialsConfig
from materials.views import MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView, \
    MaterialDeleteView, HomeView

app_name = MaterialsConfig.name


urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('create/', MaterialCreateView.as_view(), name='product_create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MaterialDeleteView.as_view(), name='delete'),


]

user/urls.py
from django.urls import path
from django.conf.urls.static import static
from config import settings
from user.apps import UserConfig
from user.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, \
    UserConfirmEmailView, UserConfirmView, UserConfirmFailView, UserConfirmSentView, IndexView

app_name = UserConfig.name




urlpatterns = [

    path('', IndexView.as_view(), name='index_main'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),

    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmView.as_view(), name='email_confirmed'),
    path('email_info_failed/', UserConfirmFailView.as_view(), name='email_info_failed'),
    path('email_senting/', UserConfirmSentView.as_view(), name='email_senting'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/models.py
from django.db import models
from django.utils import timezone


NULLABLE = {'null': True}


class Material(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    body = models.TextField(max_length=1000, verbose_name='содержимое')
    image = models.ImageField(**NULLABLE, verbose_name='Изображение')
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    views_count = models.IntegerField(default=0,verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    slug = models.CharField(max_length=100, verbose_name='slug', null=True, blank=True)


    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'материал'
        verbose_name_plural = 'материалы'

materials/forms.py
from django import forms

from materials.models import Material


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'





class MaterialForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Material
        fields = 'title', 'body', 'image'

materials/views.py
from django.http import Http404
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView

from client.models import Client
from client_service.models import SettingMailing
from client_service.service import get_cached_main
from materials.models import Material
from django.urls import reverse_lazy, reverse
from pytils.translit import slugify

from .forms import MaterialForm
from .func_send import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'materials/main.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['count_mailings'] = SettingMailing.objects.all().count()
        context_data['count_mailings_is_active'] = SettingMailing.objects.filter(status=SettingMailing.STARTED).count()
        context_data['clients_count'] = Client.objects.all().order_by('email').distinct('email').count()
        context_data['random_blog'] = Material.objects.order_by('?')[:3]
        context_data['object_list'] = get_cached_main()

        return context_data


class MaterialCreateView(CreateView):
    model = Material
    form_class = MaterialForm
    success_url = reverse_lazy('materials:list')

    # def form_valid(self, form):
    #     if form.is_valid():
    #         new_mat = form.save()
    #         new_mat.slug = slugify(new_mat.title)
    #         new_mat.save()
    #
    #     return super().form_valid(form)

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:list')

class MaterialListView(ListView):
    model = Material

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset



class MaterialDetailView(DetailView):
    model = Material

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        if self.object.views_count == 100:
            send_mail()
        return self.object



class MaterialUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Material
    form_class = MaterialForm
    success_url = reverse_lazy('materials:list')
    permission_required = ['materials.change_material']
    # success_url = reverse_lazy('materials:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)



    def get_success_url(self):
        return reverse('materials:view', args=[self.kwargs.get('pk')])

class MaterialDeleteView(PermissionRequiredMixin, DeleteView):
    model = Material
    success_url = reverse_lazy('materials:list')
    permission_required = ['materials.change_material']



class UserConfirmFailView(View):
    """ Выводит информацию об успешной регистрации пользователя """
    template_name = 'materials/not_delete_confirmed.html'

materials/templates/materials/main.html
{% extends "user/base.html" %}
{% load my_tags %}
{% block content%}


  <div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h1 class="display-5">Всего рассылок: {{ count_mailings }}</h1>
        <h1 class="display-5">Активных рассылок: {{ count_mailings_is_active }}</h1>
        <h1 class="display-5">Уникальных клиентов: {{ clients_count }}</h1>

      {% for blog in random_blog %}
        <div class="col">
          <div class="card shadow-sm">
              <img src="{{ blog.image|mymedia }}" class="bd-placeholder-img card-img-top" width="100%" height="725"
                   role="img">
            <div class="card-body mb-5">
              <p class="card-text">{{ blog|title }}({{ blog.slug }})</p>
                <p class="text-center"> {{ blog.text }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-body-secondary">Автор скрыт</small>
                <small class="text-body-secondary">{{ blog.created }}</small>
                <small class="text-body-secondary">{{ blog.views_count }} Просмотров</small>
                <a class="btn btn-info mb-3" href="{% url 'materials:list' %}" role="button">Просмотр</a>
              </div>
            </div>

          </div>
        </div>
      {% endfor %}

    </div>
  </div>
{% endblock %}

materials/templates/materials/material_confirm_delete.html
{% extends 'user/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить материал {{ object.title }}?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'materials:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'user/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12">

    <div class="row">
        <div class="col-6">
            <div class="card">
                <img class="card-img-top"
                     src="{{ object.image|mymedia }}"
                     alt="Card image cap">
                <div class="card-header">
                    <h3 class="card-title">
                        Материал "{{ object.title }}"
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>
                    <div class="card-footer">
                        Просмотры: {{ object.views_count }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

materials/templates/materials/material_form.html
{% extends 'user/base.html' %}

{% block content %}

<div class="col-12">
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>

                </div>
            </div>
        </div>
    </div>
    </form>
</div>
{% endblock %}

materials/templates/materials/material_list.html
{% extends 'user/base.html' %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'materials:product_create' %}">Добавить статью</a>
</div>
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top"
                 src="{{ object.image|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name }}</p>
                <span class="text-muted">{{ object.owner|default:"Еще не было регистрации,тест" }}</span>
                <div class="card-footer">
                    <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'materials:view' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Просмотр</a>
                        {% if perms.materials.change_material %}
                        <a href="{% url 'materials:edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Редактировать</a>
                        {% endif %}
                        {% if perms.materials.delete_material %}
                        <a href="{% url 'materials:delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-danger">Удалить</a>
                        {% endif %}
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}

materials/templates/materials/not_delete_confirmed.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Ошибка</h4>
    <p>Вы не можете удалить этот пост!</p>
</div>

{% endblock %}