client/urls.py
from django.contrib import admin
from django.urls import path
from client.apps import ClientConfig
from client.views import ClientListView, ClientCreateView, ClientUpdateView, \
    ClientDetailView, ClientDeleteView

app_name = ClientConfig.name

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ClientListView.as_view(), name='list'),
    path('create/', ClientCreateView.as_view(), name='create'),
    path('view/<int:pk>/', ClientDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', ClientUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ClientDeleteView.as_view(), name='delete'),
]

client_service/urls.py
from django.urls import path
from client_service.apps import ClientServiceConfig
from client_service.views import SettingMailingListAPIView, SettingMailingUpdateView, \
MessageDeleteView, SettingMailingDetailView,  MessageListView, MessageCreateView, MessageUpdateView, MessageDetailView,\
SettingMailingCreateView, SettingMailingDeleteView, LogsListView, toggle_active \
# ,SettingMailingListView)


app_name = ClientServiceConfig.name


urlpatterns = [

    path('messages/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('list/', SettingMailingListAPIView.as_view(), name='list'),
    # path('list/', SettingMailingListView.as_view(), name='list'),
    path('toggle-active/<int:pk>/', toggle_active, name='toggle_active'),
    path('view/<int:pk>/', SettingMailingDetailView.as_view(), name='view'),
    path('create/', SettingMailingCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', SettingMailingUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', SettingMailingDeleteView.as_view(), name='delete'),

    path('logs', LogsListView.as_view(), name='log_list'),
    # path('log/<int:pk>/', LogsDetailView.as_view(), name='log_detail'),
    # path('log_delete/<int:pk>/', LogsDeleteView.as_view(), name='log_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='users')),
    path('client/', include('client.urls', namespace='client')),
    path('client_service/', include('client_service.urls', namespace='client_service')),
    path('materials/', include('materials.urls', namespace='materials')),
]
if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path
from materials.apps import MaterialsConfig
from materials.views import MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView, \
    MaterialDeleteView, HomeView

app_name = MaterialsConfig.name


urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('create/', MaterialCreateView.as_view(), name='product_create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', MaterialDeleteView.as_view(), name='delete'),


]

user/urls.py
from django.urls import path
from django.conf.urls.static import static
from config import settings
from user.apps import UserConfig
from user.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, \
    UserConfirmEmailView, UserConfirmView, UserConfirmFailView, UserConfirmSentView, IndexView

app_name = UserConfig.name




urlpatterns = [

    path('', IndexView.as_view(), name='index_main'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),

    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmView.as_view(), name='email_confirmed'),
    path('email_info_failed/', UserConfirmFailView.as_view(), name='email_info_failed'),
    path('email_senting/', UserConfirmSentView.as_view(), name='email_senting'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from client.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    telegram = models.CharField(max_length=150, verbose_name='телеграм пользователя', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)

    # email_verify = models.BooleanField(default=False, verbose_name='проверка почты')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from user.models import User
from client.forms import StyleFormMixin
from django import forms

class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'telegram', 'avatar')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        self.fields['password'].widget = forms.HiddenInput()

user/views.py
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator

from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from client.models import Client
from client_service.models import SettingMailing
from client_service.service import get_cached_main
from materials.models import Material
from user.forms import UserRegisterForm, UserForm
from user.models import User
from django.utils.encoding import force_bytes
from django.views import View
from django.contrib.auth import login
from django.contrib.auth.views import PasswordResetDoneView

from user.services import send_mail_password, send_mail_ready


class IndexView(TemplateView):
    template_name = 'user/index_main.html'
    extra_context = {
        'title': 'Категории'
    }

class LoginView(BaseLoginView):
    template_name = 'user/login.html'

class LogoutView(BaseLogoutView):
    template_name = 'user/logout.html'


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('user:login')
    template_name = 'user/register.html'



    def form_valid(self, form):
        new_user = form.save()
        new_user.is_active = False
        new_user.save()

        token = default_token_generator.make_token(new_user)
        uid = urlsafe_base64_encode(force_bytes(new_user.pk))
        activation_url = reverse_lazy('user:confirm_email', kwargs={'uidb64': uid, 'token': token})

        current_site = '127.0.0.1:8000'
        send_mail_ready(new_user.email, current_site, activation_url)
        return redirect('user:email_senting')


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('user:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


# def generate_new_password(request):
#     new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
#     send_mail(
#         subject='Вы сменили пароль',
#         message=f'Ваш пароль: {new_password}!',
#         from_email=settings.EMAIL_HOST_USER,
#         recipient_list=[request.user.email]
#     )
#     request.user.set_password(new_password)
#     request.user.save()
#     return redirect(reverse('catalog:index_main'))


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    request.user.set_password(new_password)
    request.user.save()
    send_mail_password(request.user.email, new_password)
    return redirect(reverse('catalog:index_main'))




class UserConfirmEmailView(View):

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('user:email_confirmed')
        else:
            return redirect('user:email_info_failed')

class UserConfirmView(TemplateView):
    """ Выводит информацию об успешной регистрации пользователя """
    template_name = 'user/registration_confirmed.html'

class UserConfirmFailView(View):
    """ Выводит информацию о невозможности зарегистрировать пользователя """
    template_name = 'user/email_info_failed.html'


class UserConfirmSentView(PasswordResetDoneView):
    """ Выводит информацию об отправке на почту подтверждения регистрации """
    template_name = "user/registration_sented.html"

user/templates/user/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Сервис рассылок</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>

  <body>

<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Обрадуй письмом ближнего своего!</h4>
          <p class="text-muted">Здесь можно написать важное</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Меню</h4>
          <ul class="list-unstyled">
            <li><a href="{% url 'materials:home' %}" class="text-white">Главная</a></li>
            <li><a href="{% url 'materials:list' %}" class="text-white">Блог</a></li>
            <li><a href="{% url 'client:list' %}" class="text-white">Клиенты</a></li>

              {% if user.is_authenticated %}
                <li><a href="{% url 'user:profile' %}" class="text-white">Профиль</a></li>
                <li><a href="{% url 'client_service:list' %}" class="text-white">Рассылки</a></li>
              <li><a href="{% url 'client_service:message_list' %}" class="text-white">Сообщения для рассылок</a></li>
              <li><a href="{% url 'client_service:log_list' %}" class="text-white">Логи</a></li>
              <li><a href="{% url 'user:logout' %}" class="text-white">Выход</a></li>
              {% else %}
                <li><a href="{% url 'user:login' %}" class="text-white">Вход</a></li>
              <li><a href="{% url 'user:register' %}" class="text-white">Регистрация</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark box-shadow">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
        <strong>Рассылай, но не переусердствуй</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Кликай по меню, выбирай раздел</h1>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
          {% block content %}
          {% endblock %}


        </div>
      </div>

    </main>

  <footer class="pt-3 my-md-3 pt-md-3 border-top">
        <div class="row">

            <div class="col-6 col-md m-4">
                <h5>Все права защищены и немножко украдены</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">РАССЫЛКИ</a></li>
                </ul>
            </div>
            <div class="col-6 col-md m-4">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">написать нам</a></li>
                    <li><a class="text-muted" href="#">Что-то еще</a></li>
                    <li><a class="text-muted" href="#">О нас</a></li>
                </ul>
            </div>
          <div class="col-12 col-md m-4">
                Шлём всё и всем, и всех и вся.
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
        </div>
    </footer>


    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">НАВЕРХ</a>
        </p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>

  </body>
</html>

user/templates/user/email_info_failed.html
{% extends 'user/base.html' %}

{% block content %}

<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка</h4>
    <p>Не удалось подтвердить вашу электронную почту. Попробуйте еще раз</p>
</div>

{% endblock %}

user/templates/user/index_main.html
{% extends 'user/base.html' %}

{% block content %}
<div class="row">
    {% for object in object_list %}
        {% include 'user/includes/inc_category.html' with object=object %}
    {% endfor %}
</div>
{% endblock %}

user/templates/user/login.html
{% extends 'user/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {%  csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Вход</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>

{% endblock %}

user/templates/user/register.html
{% extends 'user/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {%  csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>

{% endblock %}

user/templates/user/registration_confirmed.html
{% extends 'user/base.html' %}

{% block content %}

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Успешно</h4>
    <p>Ваша электронная почта подтверждена</p>
</div>

{% endblock %}

user/templates/user/registration_sented.html
{% extends 'user/base.html' %}

{% block content %}

<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Вам на почту, указанную при регистрации, отправлено письмо</h4>
    <br>
    <p>Для успешной регистрации перейдите по ссылке, указанной в письме</p>
</div>

{% endblock %}

user/templates/user/user_form.html
{% extends 'user/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                  Мой профиль
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {%  csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
                <div class="card-footer">
                    <a href="{% url 'user:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}