client_service/urls.py
from django.urls import path
from client_service.apps import ClientServiceConfig
from client_service.views import SettingMailingListAPIView, SettingMailingUpdateView, \
MessageDeleteView, SettingMailingDetailView,  MessageListView, MessageCreateView, MessageUpdateView, MessageDetailView,\
SettingMailingCreateView, SettingMailingDeleteView, LogsListView, toggle_active \
# ,SettingMailingListView)


app_name = ClientServiceConfig.name


urlpatterns = [

    path('messages/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('list/', SettingMailingListAPIView.as_view(), name='list'),
    # path('list/', SettingMailingListView.as_view(), name='list'),
    path('toggle-active/<int:pk>/', toggle_active, name='toggle_active'),
    path('view/<int:pk>/', SettingMailingDetailView.as_view(), name='view'),
    path('create/', SettingMailingCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', SettingMailingUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', SettingMailingDeleteView.as_view(), name='delete'),

    path('logs', LogsListView.as_view(), name='log_list'),
    # path('log/<int:pk>/', LogsDetailView.as_view(), name='log_detail'),
    # path('log_delete/<int:pk>/', LogsDeleteView.as_view(), name='log_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='users')),
    path('client/', include('client.urls', namespace='client')),
    path('client_service/', include('client_service.urls', namespace='client_service')),
    path('materials/', include('materials.urls', namespace='materials')),
]
if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf.urls.static import static
from config import settings
from user.apps import UserConfig
from user.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_new_password, \
    UserConfirmEmailView, UserConfirmView, UserConfirmFailView, UserConfirmSentView, IndexView

app_name = UserConfig.name




urlpatterns = [

    path('', IndexView.as_view(), name='index_main'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),

    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmView.as_view(), name='email_confirmed'),
    path('email_info_failed/', UserConfirmFailView.as_view(), name='email_info_failed'),
    path('email_senting/', UserConfirmSentView.as_view(), name='email_senting'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client_service/models.py
from django.db import models

from client.models import Client
from config import settings
from user.models import User

NULLABLE = {'blank': True, 'null': True}


class MessageMailing(models.Model):
    """
    суть рассылки, тема и тело сообщения!
    """
    title = models.CharField(max_length=100, verbose_name='Тема письма')
    text = models.TextField(verbose_name='Письмо')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    # mailing_list = models.ForeignKey('SettingMailing', on_delete=models.CASCADE, verbose_name='рассылка',
    #                                  related_name='messages', **NULLABLE)
    def __str__(self):

        return f'message title:{self.title}'

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        ordering = ('title',)

class SettingMailing(models.Model):
    """
    Параметры настройки по которым будет осуществляться рассылка
    время рассылки;
    периодичность: раз в день, раз в неделю, раз в месяц;
    статус рассылки: завершена, создана, запущена.
    """

    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    PERIODICITY_CHOICES = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = 'Создана'
    STARTED = 'Запущена'
    COMPLETED = 'Завершена'

    STATUS_CHOICES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
    ]

    ACTIVE_CHOICES = ((True, 'Активна'), (False, 'На модерации'))


    recipients = models.ManyToManyField(Client, verbose_name='получатели', related_name='recipients')
    start_time = models.DateTimeField(verbose_name='Дата начала рассылки')
    end_time = models.DateTimeField(verbose_name='Дата окончания рассылки')
    periodicity = models.CharField(choices=PERIODICITY_CHOICES, max_length=50, verbose_name='Периодичность')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=CREATED, verbose_name='Статус рассылки')
    # owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)
    is_active = models.BooleanField(default=True, choices=ACTIVE_CHOICES, verbose_name='Активна')
    message = models.ForeignKey(MessageMailing, on_delete=models.SET_NULL, verbose_name='Сообщение', **NULLABLE)

    def __str__(self):
        return f'{self.recipients}'


    class Meta:
        verbose_name = 'настройки рассылок'
        verbose_name_plural = 'настройки рассылок'


class Logs(models.Model):
    """
    # Логи рассылки:
    дата и время последней попытки;
    статус попытки;
    ответ почтового сервера, если он был.
    """

    time = models.DateTimeField(verbose_name='Дата и время создания лога', auto_now_add=True)
    status_try = models.BooleanField(verbose_name='Статус попытки', **NULLABLE)
    server_response = models.CharField(max_length=1000, verbose_name='Ответ почтового сервера', **NULLABLE)
    mailing = models.ForeignKey(SettingMailing, on_delete=models.CASCADE, verbose_name='Рассылка')


    def __str__(self):
        return f'{self.time} {self.status_try}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'
        ordering = ('-time',)

client_service/forms.py
from django.forms import ModelForm

from client.models import Client
from client_service.models import MessageMailing, SettingMailing


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class SettingMailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = SettingMailing
        fields = ('start_time', 'end_time', 'periodicity', 'recipients', 'message', 'status',)


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = MessageMailing
        fields = ('title', 'text',)

client_service/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView, TemplateView
from client_service.forms import MessageForm, SettingMailingForm
from client_service.models import MessageMailing, SettingMailing, Logs
from client_service.service import get_cached_log
from client_service.serializers import SettingMailingSerializer
from rest_framework.generics import ListAPIView


class MessageListView(ListView):
    model = MessageMailing

    def get_queryset(self):
        user = self.request.user
        if user.is_staff or user.is_superuser:  # для работников и суперпользователя
            queryset = super().get_queryset()
        else:  # для остальных пользователей
            queryset = super().get_queryset().filter(owner=user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        user = self.request.user
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Список Сообщений'
        return context_data


class MessageCreateView(CreateView):
    model = MessageMailing
    form_class = MessageForm
    success_url = reverse_lazy('client_service:message_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(UpdateView):
    model = MessageMailing
    form_class = MessageForm
    success_url = reverse_lazy('client_service:message_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageDetailView(DetailView):
    model = MessageMailing

    def get_object(self, queryset=None, **kwargs):
        self.object = super().get_object(queryset)
        return self.object

class MessageDeleteView(DeleteView):
    model = MessageMailing
    success_url = reverse_lazy('client_service:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        return self.object


class SettingMailingCreateView(LoginRequiredMixin, CreateView):
    model = SettingMailing
    form_class = SettingMailingForm
    extra_context = {'title': 'Создание'}

    def get_initial(self):
        initial = super().get_initial()
        initial['owner'] = self.request.user
        return initial

    def get_success_url(self):
        return reverse('client_service:list')


class SettingMailingUpdateView(LoginRequiredMixin, UpdateView):
    model = SettingMailing
    form_class = SettingMailingForm
    extra_context = {'title': 'Редактирование'}

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

    def get_initial(self):
        initial = super().get_initial()
        initial['owner'] = self.request.user
        return initial

    def get_success_url(self):
        return reverse('client_service:view', args=[self.object.pk])


class SettingMailingListAPIView(ListAPIView):
    queryset = SettingMailing.objects.all()
    serializer_class = SettingMailingSerializer

# class SettingMailingListView(LoginRequiredMixin, ListView):
#     model = SettingMailing
#
#     def get_queryset(self):
#         user = self.request.user
#         if user.is_staff or user.is_superuser:  # для работников и суперпользователя
#             queryset = super().get_queryset()
#         else:  # для остальных пользователей
#             queryset = super().get_queryset().filter(owner=user)
#         return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Список рассылок'
        context_data['all'] = context_data['object_list'].count()
        context_data['active'] = context_data['object_list'].filter(status=SettingMailing.STARTED).count()
        context_data['completed'] = context_data['object_list'].filter(status=SettingMailing.COMPLETED).count()
        return context_data


def toggle_active(request, pk):
    if request.user.is_staff:
        client_service = SettingMailing.objects.get(pk=pk)
        client_service.is_active = not client_service.is_active
        client_service.save()
        return redirect('client_service:list')


class SettingMailingDetailView(LoginRequiredMixin, DetailView):
    model = SettingMailing

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = f'Детали рассылки:'
        return context_data


class SettingMailingDeleteView(LoginRequiredMixin, DeleteView):
    model = SettingMailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser:
            if self.object.owner != self.request.user or self.request.user.filter(groups__name='manager').exists():
                raise Http404
        return self.object

    def get_success_url(self):
        return reverse('client_service:list')


class LogsListView(LoginRequiredMixin, ListView):
    model = Logs
    template_name = 'mailing/log_list.html'

    def get_queryset(self):
        queryset = super().get_queryset().all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['all'] = context_data['object_list'].count()
        context_data['success'] = context_data['object_list'].filter(status_try=True).count()
        context_data['error'] = context_data['object_list'].filter(status_try=False).count()
        context_data['object_list'] = get_cached_log()

        return context_data

client_service/templates/client_service/logs_confirm_delete.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">
            <h5 class="card-title">Хотите удалить Лог</h5>
            <p class="card-text mb-3">Дата попытки: {{ object.time }}</p>
            <p class="card-text mb-3">Статус: {{ object.status }}</p>
            <p class="card-text mb-3">Ответ сервера: {{ object.server_response }}</p>
            {% if user.is_staff %}
            <p class="card-text mb-3">Автор: {{ object.owner }}</p>
            {% endif %}
            <a href="{% url 'distribution:view' object.mailing.pk %}" type="button"
               class="btn btn-sm btn-outline-secondary">К рассылке</a>
        </div>
        <div class="card-footer">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg btn-block btn btn-danger">удалить</button>
                <a type="button" href="{% url 'client_service:log_list'%}"
                   class="btn btn-lg btn-block btn-outline-primary">назад</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

client_service/templates/client_service/logs_detail.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">

            <p class="card-text mb-3">Дата попытки: {{ object.time }}</p>
            <p class="card-text mb-3">Статус: {{ object.status }}</p>
            <p class="card-text mb-3">Ответ сервера: {{ object.server_response }}</p>
            {% if user.is_staff %}
            <p class="card-text mb-3">Автор: {{ object.owner }}</p>
            {% endif %}

            <a href="{% url 'client_service:view' object.mailing.pk %}" type="button"
               class="btn btn-sm btn-outline-secondary">К рассылке</a>
        </div>
        <div class="card-footer">

            <a type="button" href="{% url 'client_service:log_list'%}"
               class="btn btn-lg btn-block btn-outline-primary">назад</a>

        </div>
    </div>
</div>

{% endblock %}

client_service/templates/client_service/logs_list.html
{% extends 'user/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Логи</h1>
</div>

<div class="container col-12 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <tr>
                            <th><h4>Количество отправленных писем</h4></th>
                            <th><h4>Количество успешно отправленных писем</h4></th>
                            <th><h4>Количество ошибок</h4></th>
                        </tr>
                        <body>
                        <tr>
                            <td><h4>{{ all }}</h4></td>
                            <td><h4>{{ success }}</h4></td>
                            <td><h4>{{ error }}</h4></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container col-12">
    <div class="card">
        <div class="card-header text-center">
            <h1>Рассылки</h1>
        </div>
        <div class="card-body">
            <div class="col-12">
                <table class="table text-center">
                    <tr>
                        <th><h4>Время рассылки</h4></th>
                        <th><h4>Название рассылки</h4></th>
                        <th><h4>Статус</h4></th>
                        <th><h4>Ответ сервера</h4></th>
                        <th><h4>Ответственный</h4></th>
                        <th><h4>Статус рассылки</h4></th>
                    </tr>
                    {% for object in object_list %}
                    <tr>
                        <td><h4>{{ object.time }}</h4></td>
                        <td><h4>{{ object.mailing.message.title }}</h4></td>
                        <td><h4>{{ object.status_try }}</h4></td>
                        <td><h4>{{ object.server_response }}</h4></td>
                        <td><h4>{{ object.mailing.message.owner }}</h4></td>
                        <td><h4>
                            {% if object.status_try %}
                            <p style="color:rgb(13, 209, 13)">Успешно</p>
                            {% else %}
                            <p style="color:rgb(173, 11, 11)">Ошибка</p>
                            {% endif %}
                        </h4></td>
                        {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {% endblock %}

client_service/templates/client_service/message_confirm_delete.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">
            <h5 class="card-title">Can you delete message</h5>
            <h5 class="card-title">title: {{ message.title }}</h5>
            <p class="card-title">text: {{ message.text }}</p>
            {% if request.user.is_staff %}
            <p class="card-text mb-3">owner: {{ message.owner }}</p>
            {% endif %}
        </div>
        <div class="card-footer">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Delete</button>
                <a type="button" href="{% url 'client_service:message_list'%}"
                   class="btn btn-lg btn-block btn-outline-primary">return</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

client_service/templates/client_service/message_form.html
{% extends "user/base.html" %}

{% block content %}

<div class="text-center container">
    <form method="post">
        <div class="card col-8">
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a type="button" href="{% url 'client_service:message_list'%}"
                   class="btn btn-lg btn-block btn-outline-primary">return</a>

            </div>
        </div>
    </form>
</div>

{% endblock %}

client_service/templates/client_service/message_list.html
{% extends 'user/base.html' %}
{% load my_tags %}
{% block content %}

{% if not user|has_group:"manager" %}
<div class="text-center container">
    <a class="btn btn-primary" href="{% url 'distribution:message_create' %}" type="button">Add Message</a>
</div>
{% endif %}

<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Message</th>
            {% if request.user.is_staff %}
            <th scope="col">owner</th>
            {% endif %}
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>

        {% for message in object_list %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ message.title|truncatechars:25 }}</td>
            <td>{{ message.text|truncatechars:25 }}</td>
            {% if request.user.is_staff %}
            <td>{{ message.owner }}</td>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'distribution:message_view' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">View</a>
                    {% if not user|has_group:"manager" %}
                    <a href="{% url 'distribution:message_edit' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Edit</a>
                    <a href="{% url 'distribution:message_delete' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">Delete</a>
                    {% endif %}
                </div>
            </td>
        </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}

client_service/templates/client_service/messagemailing_confirm_delete.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">
            <h5 class="card-title">Удалить сообщение</h5>
            <h5 class="card-title">заголовок: {{ object.title }}</h5>
            <p class="card-title">текст: {{ object.text }}</p>
            {% if request.user.is_staff %}
            <p class="card-text mb-3">создатель: {{ object.owner }}</p>
            {% endif %}
        </div>
        <div class="card-footer">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">удалить</button>
                <a type="button" href="{% url 'client_service:message_list'%}"
                   class="btn btn-lg btn-block btn-outline-primary">назад</a>
            </form>
        </div>
    </div>
</div>

{% endblock %}

client_service/templates/client_service/messagemailing_detail.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">

            <h5 class="card-title">заголовок: {{ object.title }}</h5>
            <p class="card-title">текст: {{ object.text }}</p>

        </div>

        <div class="card-footer">

            {% if request.user.is_staff %}
            <p class="card-text mb-3">создатель: {{ object.owner }}</p>
            {% endif %}
            <a type="button" href="{% url 'client_service:message_list'%}"
               class="btn btn-lg btn-block btn-outline-primary">назад</a>

        </div>

    </div>
</div>

{% endblock %}

client_service/templates/client_service/messagemailing_form.html
{% extends "user/base.html" %}

{% block content %}

<div class="text-center container">
    <form method="post">
        <div class="card col-8">
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a type="button" href="{% url 'client_service:message_list'%}"
                   class="btn btn-lg btn-block btn-outline-primary">назад</a>

            </div>
        </div>
    </form>
</div>

{% endblock %}

client_service/templates/client_service/messagemailing_list.html
{% extends 'user/base.html' %}
{% load my_tags %}
{% block content %}

{% if user.is_authenticated %}
<div class="text-center container">
    <a class="btn btn-primary mb-2" href="{% url 'client_service:message_create' %}" type="button">Добавить сообщение</a>
</div>
{% endif %}

<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Заголовок</th>
            <th scope="col">Текст</th>
            {% if request.user.is_staff %}
            <th scope="col">создатель</th>
            {% endif %}
            <th scope="col">действие</th>
        </tr>
        </thead>
        <tbody>

        {% for message in object_list %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ message.title|truncatechars:25 }}</td>
            <td>{{ message.text|truncatechars:25 }}</td>
            {% if request.user.is_staff %}
            <td>{{ message.owner }}</td>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'client_service:message_view' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">смотреть</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'client_service:message_edit' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">изменить</a>
                    <a href="{% url 'client_service:message_delete' message.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">удалить</a>
                    {% endif %}
                </div>
            </td>
        </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}

client_service/templates/client_service/settingmailing_detail.html
{% extends 'user/base.html' %}

{% block content %}

<div class="container">
    <div class="card col-8">
        <div class="card-body">


            <p class="card-title">начало рассылки: {{ object.start_time }}</p>
            <p class="card-title">окончание рассылки: {{ object.end_time }}</p>
            <p class="card-title">периодичность: {{ object.periodicity }}</p>
            <p class="card-title">статус: {{ object.status }}</p>
            <p class="card-title">сообщение: {{ object.message }}</p>
            <p class="card-title">клиенты:
                {% for item in object.clients.all %}
                    {{ item.email }},
                {% endfor %}
            </p>

        </div>
        <div class="card-footer">

            {% if request.user.is_staff %}
            <p class="card-text mb-3">owner: {{ object.owner }}</p>
            {% endif %}
            <a type="button" href="{% url 'client_service:list'%}"
               class="btn btn-lg btn-block btn-outline-primary">назад</a>

        </div>
    </div>
</div>

{% endblock %}

client_service/templates/client_service/settingmailing_list.html
{% extends 'user/base.html' %}
{% load my_tags %}
{% block content %}

{% if user.is_authenticated %}
<div class="text-center container">
    <a class="btn btn-primary" href="{% url 'client_service:create' %}" type="button">Добавить</a>
</div>
{% endif %}

<div class="container col-8 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <thead>
                        <tr>
                            <th><h4>Количество рассылок</h4></th>
                            <th><h4>Количество активных рассылок</h4></th>
                            <th><h4>Количество завершенных рассылок</h4></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><h4>{{ all }}</h4></td>
                            <td><h4>{{ active }}</h4></td>
                            <td><h4>{{ completed }}</h4></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container text-center">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">время отправки</th>
            <th scope="col">начало рассылки</th>
            <th scope="col">конец рассылки</th>
            <th scope="col">периодичность</th>
            <th scope="col">статус</th>
            <th scope="col">актуальность</th>
            {% if request.user.is_staff %}
            <th scope="col">создатель</th>
            {% endif %}
            <th scope="col">действия</th>
        </tr>
        </thead>
        <tbody>

        {% for client_service in object_list %}

        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ client_service.next_send }}</td>
            <td>{{ client_service.start_time }}</td>
            <td>{{ client_service.end_time }}</td>
            <td>{{ client_service.periodicity }}</td>
            <td>{{ client_service.status }}</td>
            {% if request.user.is_staff %}
            {% if client_service.is_active %}
            <td>
                <a href="{% url 'client_service:toggle_active' client_service.pk %}" type="button"
                   class="btn btn-success">True</a>
            </td>
            {% else %}
            <td>
                <a href="{% url 'client_service:toggle_active' client_service.pk %}" type="button"
                   class="btn btn-danger">False</a>
            </td>
            {% endif %}
            <td>{{ client_service.owner }}</td>
            {% else %}
            <td>{{ client_service.is_active }}</td>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="{% url 'client_service:view' client_service.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">смотреть</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'client_service:edit' client_service.pk %}" type="button"
                       class="btn btn-sm btn-outline-secondary">изменить</a>
                    <a href="{% url 'client_service:delete' client_service.pk %}" type="button"
                       class="btn btn-sm btn btn-danger">удалить</a>
                    {% endif %}
                </div>
            </td>
        </tr>

        {% endfor %}

        </tbody>
    </table>
</div>

{% endblock %}